[package]
name = "resfork-extract"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
zip = { version = "0.5", default-features = false, features = ["deflate", "time"] }

[profile.release]
opt-level = 2
panic = "abort"
