[package]
name = "resfork-extract"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
winapi = { version = "0.3", features = ["wingdi"] }
zip = { version = "0.5", default-features = false, features = ["deflate"] }
